### ISSUE TITLE
Capture dcCreator as text

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/object-store-specs#64]
It has been suggested to capture `dcCreator` as text instead of a pointer to an Agent. The current suggestion was to use `dcCreator` to capture, for example, the photographer. Based on feedback, the person taking the picture would not necessarily be an agent (e.g. students, volunteers).

**Comment by dshorthouse** [comment]
I disagree with this. It is a regression & counter to our notion of what the Agent module is supposed to do. All users are agents but not all agents are users. However, some agents do have the potential to *eventually* become users.

The tension here is where and how to disambiguate agents and this gets back to our discussion on where the dirty bucket of unreconciled agent strings should reside (if there is to be one) and where and how the dirty bucket gets populated. `dcCreator` is the first and definitely not the last of the fields where we'd have a need to store an Agent string. The question is, do we want these Agent strings in multiple modules or do we want them in one place such that we can use these linkages to better disambiguate (= merge) whether or not one Agent string is the same person as another Agent string?

**Comment by cgendreau** [comment]
I think the Agent strings should only live in the agent module sure fore (single source of truth). Would you suggest to introduce the dirty bucket in the API specs (like verbatimDcCreator)?

**Comment by ssbilkhu** [comment]
I think we need to settle on a choice for Release 1.

**Comment by dshorthouse** [comment]
This is our first test of what linking means in DINA. And it's an easy one. If we strip it out & replace it with a string column to satisfy immediate needs, what is the outcome and what is the alternate architecture? 

Or, might there be a middle ground where the Agent module is used as a remote gazetteer of sorts? When a user creates a new entry in a text field such as this `dcCreator` in a new multimedia record, an entry is transparently pushed into / selected from the Agent module (= `findOrCreateBy`). In practice, this means a many:many link between a dirty bucket list in the Agent module and linked assets elsewhere. And then, when dirty Agent strings are later reconciled to some external identifiers like ORCID or other, there would be an opportunity to see all likely candidate Agent strings to be reconciled + their linkages to assets / data objects. These Agents would be stored as a "clean bucket" table, also in the Agent module.

To be sure, the above is half-baked, but how much are we willing to sacrifice & defer?

**Comment by ssbilkhu** [comment]
I am leaning towards creating agents for this field.  I also think that the feedback we get from a few months of usage of Release 1 will show us if we are in the right direction or not with this choice and many other areas.

**Comment by dshorthouse** [comment]
@ssbilkhu – it does mean that *someone* has to create the Agent records, and this is not always an easy thing to do. It puts the onus on the user to mentally reconcile who the Agent is while simultaneously entering new data. That can be a jolting experience. There will eventually be tens of thousands of Agents. "Is this M. Smith" photographer the same as that "M. Smith" collector? In time, a drop-down will need to be replaced w/ an autocomplete text field because there will be too many Agents rolling through a drop-down.

**Comment by cgendreau** [comment]
That would not be an issue for now and having autocomplete field is not an issue. I think most of the issues above can be addressed by ui/ux so I'm also in favor in keeping the current approach (the agent has to exist) at the api level.

**Comment by jmacklin** [comment]
I generally follow David's logic when it comes to what the composition/function of the Agent "module" will be. For release 1 we are only dealing with the use case of application-based (DINA) users and if I understand correctly, this can be accomplished simply by using a text string in dcCreator to capture user names. I assume that this list will be very short. So, we could do the implementation now using this approach and then in release 2 where agents will come from a relationship to a specimen (collectors, authors, determiners...) we have to consider the approaches David has illustrated above regarding disambiguation and again decide how far we want to go to support the collection management use cases.

@ssbilkhu - I am not sure that we will learn anything from users in release 1 as they will only be dealing with known agents and thus disambiguation is not necessary. However, in release 2 this will be essential!
@cgendreau - is this what you mean by keeping the current approach?

**Comment by cgendreau** [comment]
Not exactly :)

`dcCreator` is currently a pointer to an agent in the Agent module so I would keep it like that since, as you mentioned, there is not a lot of users for now.

**Comment by shannonasencio** [comment]
Although I haven't read all of the messages above, I agree with David. Why have a dog's breakfast of how human names are handled? That is not consistent with any other CMS I have used.

**Comment by cgendreau** [comment]
Just to be clear the current status is agreement with what David said here:

> 
I disagree with this. It is a regression & counter to our notion of what the Agent module is supposed to do. All users are agents but not all agents are users. However, some agents do have the potential to eventually become users.

**Comment by shannonasencio** [comment]
Exactly! Thanks for confirming.
