### ISSUE TITLE
Unnecessary AcceptedValuesInt in managedAttribute schema

### ISSUE THREAD

**Issue by Jkeyuk** [DINA-Web/object-store-specs#66]
**update**: the issues above are not related to the schema but AcceptedValuesInt and AcceptedValuesString were unnecessary so they are removed as part of that issue.

There appears to be an issue validating the schema's during the object store tests.

`Caused by: org.openapi4j.core.exception.ResolutionException: Reference '#/components/schemas/AcceptedValuesInt' is unreachable in 'file:/.`

**Schemas paths per test:**

> SCHEMA_PATH = "DINA-Web/object-store-specs/master/schema/metadata.yaml";  
> SCHEMA_PATH = "DINA-Web/object-store-specs/master/schema/managedAttribute.yaml"; 
> SCHEMA_PATH = "DINA-Web/object-store-specs/master/schema/objectSubtype.yaml";  

I will update the issue with the current error messages

**Comment by Jkeyuk** [comment]
Current validation errors:

> Reference '#/components/schemas/CommonMetadata' is unreachable 
> Reference '#/components/schemas/CommonObjectSubtype' is unreachable 
> Reference '#/components/schemas/AcceptedValuesInt' is unreachable

**Comment by cgendreau** [comment]
Validation issues solved in the library.

AcceptedValuesInt and AcceptedValuesString removed by
https://github.com/DINA-Web/object-store-specs/pull/67
