### ISSUE TITLE
Change field type URI (instead of URL so far) for the field Resource External URL (External Resources)

### ISSUE THREAD

**Issue by nadinetamm** [DINA-Web/object-store-specs#93]
<img width="1364" alt="external_resources_url" src="https://user-images.githubusercontent.com/115980888/220885748-1ac0c79d-6c20-4454-ab87-66d9dd95d65d.png">

**Comment by cgendreau** [comment]
URI representing a file is working: `file:///c:/path/to/the%20file.txt` or `file:///etc/fstab`

**Comment by nadinetamm** [comment]
Note to us: 
Works: https:// - htpp:// - file:///das/hier/geht
Not working: uem:///das/hier/geht/nicht
